---

- hosts: bouncer
  remote_user: root
  tasks:  
    - name: "Add the user leo"
      user:
          name: leo
          comment: Leo
          uid: 1040
    - name: Install Packages
      apt:
        state: latest
        pkg: ['mosh', 'irssi']

